apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: parvazemasud/springbootapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8085

