---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: dev
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
